# Generated by Django 5.1.3 on 2025-07-28 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
    ]
